### ISSUE TITLE
Zmiana metody płatności nie działa

### ISSUE THREAD

**Issue by jacobWebDesign** [PayU-EMEA/woo-payu-payment-gateway#80]
Kiedy użytkownik próbuje zmienić metodę płatności, występuje błąd krytyczny i strona nie pozwala przejść dalej. 

Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function get_total() on bool in /mnt/data/home/hosting/mojastrona/public_html/wp-content/plugins/woo-payu-payment-gateway/Payu/Gateways/WC_Payu_Gateways.php:62\nStack trace:\n#0 /mnt/data/home/hosting/mojastrona/public_html/wp-content/plugins/woo-payu-payment-gateway/Payu/Gateways/WC_Gateway_PayuStandard.php(8): Payu\\PaymentGateway\\Gateways\\WC_Payu_Gateways->__construct()\n#1 /mnt/data/home/hosting/mojastrona/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(103): Payu\\PaymentGateway\\Gateways\\WC_Gateway_PayuStandard->__construct()\n#2 /mnt/data/home/hosting/mojastrona/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(76): WC_Payment_Gateways->init()\n#3 /mnt/data/home/hosting/mojastrona/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(49): WC_Payment_Gateways->...', referer: https://mojastrona.pl/moje-konto/view-subscription/21169

**Comment by regdos** [comment]
Zakłądam, że korzystasz z Woo Subscriptions. Nie testujemy pluginu z tym rozszerzeniem, ale mieliśmy podbobe zgłoszenie i poprawiliśmy je w wersji 2.9.1. Proszę przetestuj.
